#!/usr/bin/env bash
set -euo pipefail

if [[ ${OS:-} = Windows_NT ]]; then
    echo 'erro: Por favor user o instalador HVC do no Windows'
    exit 1
fi

# Reset
Color_Off=''

# Regular Colors
Red=''
Green=''
Dim='' # White

# Bold
Bold_White=''
Bold_Green=''

if [[ -t 1 ]]; then
    # Reset
    Color_Off='\033[0m' # Text Reset

    # Regular Colors
    Red='\033[0;31m'   # Red
    Green='\033[0;32m' # Green
    Dim='\033[0;2m'    # White

    # Bold
    Bold_Green='\033[1;32m' # Bold Green
    Bold_White='\033[1m'    # Bold White
fi

error() {
    echo -e "${Red}error${Color_Off}:" "$@" >&2
    exit 1
}

info() {
    echo -e "${Dim}$@ ${Color_Off}"
}

info_bold() {
    echo -e "${Bold_White}$@ ${Color_Off}"
}

success() {
    echo -e "${Green}$@ ${Color_Off}"
}

command -v unzip >/dev/null ||
    error 'unzip is required to install'

if [[ $# -gt 1 ]]; then
    error 'Too many arguments'
fi

case $(uname -ms) in
'Darwin x86_64')
    target=darwin-x64
    ;;
'Darwin arm64')
    target=darwin-aarch64
    ;;
'Linux x86_64' | *)
    target=linux-x64
    ;;
esac

if [[ $target = darwin-x64 ]]; then
    error "Por enquanto o script de instalação para MAC não está disponível"
    exit 1
fi

GITHUB=${GITHUB-"https://github.com"}

github_repo="$GITHUB/WilkerSebastian/HV-compiler"

hvc_uri=$github_repo/releases/latest/download/hvc-$target.zip

install_dir="$HOME/.hvc"

mkdir -p $install_dir

curl -Lo "$install_dir/hvc-$target.zip" $hvc_uri

# Verificar se o download foi bem-sucedido
if [ $? -ne 0 ]; then
    error "Falha ao baixar o arquivo $hvc_uri. Verifique sua conexão com a internet."
fi

# Verificar se o arquivo é um arquivo zip válido
if ! unzip -tq "$install_dir/hvc-$target.zip" >/dev/null; then
    error "O arquivo baixado não é um arquivo zip válido."
fi

unzip -o "$install_dir/hvc-$target.zip" -d "$install_dir"

if [[ $target = linux-x64 ]]; then

    echo "export PATH=\$PATH:$install_dir/bin" >> ~/.bashrc

    source ~/.bashrc

else

    echo "export PATH=\$PATH:$install_dir/bin" >> ~/.bash_profile

    source ~/.bash_profile

fi

success "HVC instalado com sucesso!"